# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2024-07-12T08:53:08+00:00

from __future__ import annotations

from datetime import date, time
from enum import Enum
from typing import List, Optional, Union

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    EmailStr,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class Type(Enum):
    WaterQualityObservedCAT = 'WaterQualityObservedCAT'


class TLF(BaseModel):
    pass


class EntityIdentifierType(
    RootModel[
        Union[
            constr(
                pattern=r'^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$',
                min_length=1,
                max_length=256,
            ),
            AnyUrl,
        ]
    ]
):
    root: Union[
        constr(
            pattern=r'^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$', min_length=1, max_length=256
        ),
        AnyUrl,
    ] = Field(..., description='Property. Unique identifier of the entity')


class Email(RootModel[EmailStr]):
    root: EmailStr = Field(..., description='Property. Email address of owner')


class UserAlias(RootModel[str]):
    root: str = Field(..., description='Property. An anonymous alias of a user')


class Tag(RootModel[str]):
    root: str = Field(
        ...,
        description="Property. Model:'https://schema.org/Text'. An optional text string used to qualify an item",
    )


class TimeInstant(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(
        ...,
        description="Property. Model:'https://schema.org/Datetime'. Timestamp of the payload . There can be production environments where the attribute type is equal to the `ISO8601` string. If so, it must be considered as a synonym of `DateTime`. This attribute is kept for backwards compatibility with old FIWARE reference implementations",
    )


class DateObserved(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(
        ..., description='Property. Date of the observed entity defined by the user'
    )


class DateYearLess(
    RootModel[
        constr(
            pattern=r'^--((0[13578]|1[02])-31|(0[1,3-9]|1[0-2])-30|(0\d|1[0-2])-([0-2]\d))$'
        )
    ]
):
    root: constr(
        pattern=r'^--((0[13578]|1[02])-31|(0[1,3-9]|1[0-2])-30|(0\d|1[0-2])-([0-2]\d))$'
    )


class Type1(Enum):
    Point = 'Point'


class Location(BaseModel):
    type: Type1
    coordinates: List[float] = Field(..., min_length=2)
    bbox: Optional[List[float]] = Field(None, min_length=4)


class Type2(Enum):
    LineString = 'LineString'


class Coordinate(RootModel[List[float]]):
    root: List[float]


class Location1(BaseModel):
    type: Type2
    coordinates: List[Coordinate] = Field(..., min_length=2)
    bbox: Optional[List[float]] = Field(None, min_length=4)


class Type3(Enum):
    Polygon = 'Polygon'


class Location2(BaseModel):
    type: Type3
    coordinates: List[List[Coordinate]]
    bbox: Optional[List[float]] = Field(None, min_length=4)


class Type4(Enum):
    MultiPoint = 'MultiPoint'


class Location3(BaseModel):
    type: Type4
    coordinates: List[List[float]]
    bbox: Optional[List[float]] = Field(None, min_length=4)


class Type5(Enum):
    MultiLineString = 'MultiLineString'


class Location4(BaseModel):
    type: Type5
    coordinates: List[List[Coordinate]]
    bbox: Optional[List[float]] = Field(None, min_length=4)


class Type6(Enum):
    MultiPolygon = 'MultiPolygon'


class Location5(BaseModel):
    type: Type6
    coordinates: List[List[List[Coordinate]]]
    bbox: Optional[List[float]] = Field(None, min_length=4)


class Address(BaseModel):
    streetAddress: Optional[str] = Field(
        None,
        description="Property. The street address. Model:'https://schema.org/streetAddress'",
    )
    addressLocality: Optional[str] = Field(
        None,
        description="Property. The locality in which the street address is, and which is in the region. Model:'https://schema.org/addressLocality'",
    )
    addressRegion: Optional[str] = Field(
        None,
        description="Property. The region in which the locality is, and which is in the country. Model:'https://schema.org/addressRegion'",
    )
    addressCountry: Optional[str] = Field(
        None,
        description="Property. The country. For example, Spain. Model:'https://schema.org/addressCountry'",
    )
    postalCode: Optional[str] = Field(
        None,
        description="Property. The postal code. For example, 24004. Model:'https://schema.org/https://schema.org/postalCode'",
    )
    postOfficeBoxNumber: Optional[str] = Field(
        None,
        description="Property. The post office box number for PO box addresses. For example, 03578. Model:'https://schema.org/postOfficeBoxNumber'",
    )
    streetNr: Optional[str] = Field(
        None,
        description='Property. Number identifying a specific property on a public street',
    )
    district: Optional[str] = Field(
        None,
        description='Property. A district is a type of administrative division that, in some countries, is managed by the local government',
    )


class LocationCommons(BaseModel):
    location: Optional[
        Union[Location, Location1, Location2, Location3, Location4, Location5]
    ] = Field(
        None,
        description='GeoProperty. Geojson reference to the item. It can be Point, LineString, Polygon, MultiPoint, MultiLineString or MultiPolygon',
    )
    address: Optional[Address] = Field(
        None,
        description="Property. The mailing address. Model:'https://schema.org/address'",
    )
    areaServed: Optional[str] = Field(
        None,
        description="Property. The geographic area where a service or offered item is provided. Model:'https://schema.org/Text'",
    )


class PhysicalObjectCommons(BaseModel):
    color: Optional[str] = Field(
        None,
        description="Property. The color of the product. Model:'https://schema.org/color'",
    )
    image: Optional[AnyUrl] = Field(
        None,
        description="Property. An image of the item. Model:'https://schema.org/URL'",
    )
    annotations: Optional[List[str]] = Field(
        None,
        description="Property. Annotations about the item. Model:'https://schema.org/Text'",
    )


class DayOfWeek(Enum):
    Monday = 'Monday'
    Tuesday = 'Tuesday'
    Wednesday = 'Wednesday'
    Thursday = 'Thursday'
    Friday = 'Friday'
    Saturday = 'Saturday'
    Sunday = 'Sunday'
    PublicHolidays = 'PublicHolidays'


class DayOfWeek1(Enum):
    https___schema_org_Monday = 'https://schema.org/Monday'
    https___schema_org_Tuesday = 'https://schema.org/Tuesday'
    https___schema_org_Wednesday = 'https://schema.org/Wednesday'
    https___schema_org_Thursday = 'https://schema.org/Thursday'
    https___schema_org_Friday = 'https://schema.org/Friday'
    https___schema_org_Saturday = 'https://schema.org/Saturday'
    https___schema_org_Sunday = 'https://schema.org/Sunday'
    https___schema_org_PublicHolidays = 'https://schema.org/PublicHolidays'


class OpeningHoursSpecificationItem(BaseModel):
    opens: Optional[time] = Field(
        None,
        description='Property. The opening hour of the place or service on the given day(s) of the week',
    )
    closes: Optional[time] = Field(
        None,
        description='Property.  \tThe closing hour of the place or service on the given day(s) of the week',
    )
    dayOfWeek: Optional[Union[DayOfWeek, DayOfWeek1]] = Field(
        None,
        description="Property. Model:'http://schema.org/dayOfWeek'. The day of the week for which these opening hours are valid. URLs from GoodRelations (http://purl.org/goodrelations/v1) are used (for Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday plus a special entry for PublicHolidays)",
    )
    validFrom: Optional[Union[date, AwareDatetime]] = Field(
        None,
        description='Property. The date when the item becomes valid. A date value in the form CCYY-MM-DD or a combination of date and time of day in the form [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm] in ISO 8601 date format',
    )
    validThrough: Optional[Union[date, AwareDatetime]] = Field(
        None,
        description='Property. The date after when the item is not valid. For example the end of an offer, salary period, or a period of opening hours. A date value in the form CCYY-MM-DD or a combination of date and time of day in the form [-]CCYY-MM-DDThh:mm:ss[Z|(+|-)hh:mm] in ISO 8601 date format',
    )


class DateTimeCommons(BaseModel):
    openingHoursSpecification: Optional[List[OpeningHoursSpecificationItem]] = Field(
        None,
        description="Property. A structured value providing information about the opening hours of a place or a certain service inside a place. Model:'https://schema.org/openingHoursSpecification'",
        min_length=1,
    )
    startDate: Optional[AwareDatetime] = Field(
        None,
        description="Property. Model:'https://schema.org/startDate'. The start date and time of the item (in ISO 8601 date format).",
    )
    endDate: Optional[AwareDatetime] = Field(
        None,
        description="Property. Model:'https://schema.org/endDate'. The end date and time of the item (in ISO 8601 date format).",
    )
    openingHours: Optional[str] = Field(
        None,
        description="Property. Model:'https://schema.org/openingHours'. The general opening hours for a business. Opening hours can be specified as a weekly time range, starting with days, then times per day. Multiple days can be listed with commas ',' separating each day. Day or time ranges are specified using a hyphen '-'. Days are specified using the following two-letter combinations: Mo, Tu, We, Th, Fr, Sa, Su. Times are specified using 24:00 format. For example, 3pm is specified as 15:00, 10am as 10:00. Here is an example: <time itemprop='openingHours' datetime='Tu,Th 16:00-20:00'>Tuesdays and Thursdays 4-8pm</time>. If a business is open 7 days a week, then it can be specified as <time itemprop='openingHours' datetime='Mo-Su'>Monday through Sunday, all day</time>",
    )


class ContactPoint(BaseModel):
    contactType: Optional[str] = Field(
        None, description='Property. Contact type of this item'
    )
    email: Optional[Email] = None
    telephone: Optional[str] = Field(
        None, description='Property. Telephone of this contact'
    )
    name: Optional[str] = Field(None, description='Property. The name of this item')
    url: Optional[AnyUrl] = Field(
        None,
        description='Property. URL which provides a description or further information about this item',
    )
    areaServed: Optional[str] = Field(
        None,
        description='Property. The geographic area where a service or offered item is provided. Supersedes serviceArea',
    )
    availableLanguage: Optional[Union[str, List[str]]] = Field(
        None,
        description="Property. Model:'http://schema.org/availableLanguage'. A language someone may use with or at the item, service or place. Please use one of the language codes from the IETF BCP 47 standard. It is implemented the Text option but it could be also Language",
    )
    contactOption: Optional[Union[str, List[str]]] = Field(
        None,
        description="Property. Model:'http://schema.org/contactOption'. An option available on this contact point (e.g. a toll-free number or support for hearing-impaired callers)",
    )
    faxNumber: Optional[str] = Field(
        None,
        description="Property. Model:'http://schema.org/Text'. The fax number of the item",
    )
    productSupported: Optional[str] = Field(
        None,
        description="Property. Model:'http://schema.org/Text'. The product or service this support contact point is related to (such as product support for a particular product line). This can be a specific product or product line (e.g. 'iPhone') or a general category of products or services (e.g. 'smartphones')",
    )
    availabilityRestriction: Optional[
        Union[
            List[
                constr(
                    pattern=r'^[\w\-\.\{\}\$\+\*\[\]`|~^@!, :\\]+$',
                    min_length=1,
                    max_length=256,
                )
            ],
            List[AnyUrl],
        ]
    ] = Field(
        None,
        description="Relationship. Model:'http://schema.org/hoursAvailable'. This property links a contact point to information about when the contact point is not available. The details are provided using the Opening Hours Specification class",
    )


class ContactCommons(BaseModel):
    contactPoint: Optional[ContactPoint] = Field(
        None,
        description="Property. Model:'https://schema.org/ContactPoint'. The details to contact with the item",
    )


class Person(BaseModel):
    additionalName: Optional[str] = Field(
        None,
        description="Property. Model:'https://schema.org/Text'. An additional name for a Person, can be used for a middle name",
    )
    familyName: Optional[str] = Field(
        None,
        description="Property. Model:'https://schema.org/Text'. Family name. In the U.S., the last name of a Person",
    )
    givenName: Optional[str] = Field(
        None,
        description="Property. Model:'https://schema.org/Text'. Given name. In the U.S., the first name of a Person",
    )
    telephone: Optional[str] = Field(
        None,
        description="Property. Model:'https://schema.org/Text'. The telephone number",
    )
    email: Optional[Email] = None


class PersonCommons(BaseModel):
    person: Optional[Person] = Field(
        None,
        description="Property. Model:'https://schema.org/Person'. A person (alive, dead, undead, or fictional)",
    )


class Addressable(BaseModel):
    href: Optional[AnyUrl] = Field(
        None, description='Relationship. Hyperlink reference'
    )
    id: Optional[str] = Field(None, description='Property. unique identifier')


class Extensible(BaseModel):
    field_schemaLocation: Optional[AnyUrl] = Field(
        None,
        alias='@schemaLocation',
        description='Property. A URI to a JSON-Schema file that defines additional attributes and relationships',
    )
    field_baseType: Optional[str] = Field(
        None,
        alias='@baseType',
        description='Property. When sub-classing, this defines the super-class',
    )
    field_type: Optional[str] = Field(
        None,
        alias='@type',
        description='Property. When sub-classing, this defines the sub-class Extensible name',
    )

class TimeSeriesAggregation(BaseModel):
    avgOverTime: Optional[float] = Field(
        None, description='Property. Average value over period of time'
    )
    minOverTime: Optional[float] = Field(
        None, description='Property. Minimum value over period of time'
    )
    maxOverTime: Optional[float] = Field(
        None, description='Property. Maximum value over period of time'
    )
    instValue: Optional[float] = Field(
        None, description='Property. Instant value when information is retrieved'
    )


class TouristType(Enum):
    ADVENTURE_TOURISM = 'ADVENTURE TOURISM'
    ASTRONOMY_TOURISM = 'ASTRONOMY TOURISM'
    BACKPACKING_TOURISM = 'BACKPACKING TOURISM'
    BEACH_AND_SUN_TOURISM = 'BEACH AND SUN TOURISM'
    BEER_TOURISM = 'BEER TOURISM'
    BIRDING_TOURISM = 'BIRDING TOURISM'
    BULLFIGHTING_TOURISM = 'BULLFIGHTING TOURISM'
    BUSINESS = 'BUSINESS'
    COMMUNITY_BASED_TOURISM = 'COMMUNITY-BASED TOURISM'
    CRUISE_TOURISM = 'CRUISE TOURISM'
    CULTURAL_TOURISM = 'CULTURAL TOURISM'
    CYCLING_TOURISM = 'CYCLING TOURISM'
    DIVING_TOURISM = 'DIVING TOURISM'
    ECOTOURISM = 'ECOTOURISM'
    EVENTS_AND_FESTIVALS_TOURISM = 'EVENTS AND FESTIVALS TOURISM'
    FAMILY_TOURISM = 'FAMILY TOURISM'
    FILM_TOURISM = 'FILM TOURISM'
    FISHING_TOURISM = 'FISHING TOURISM'
    FOOD_TOURISM = 'FOOD TOURISM'
    GAMBLING_TOURISM = 'GAMBLING TOURISM'
    GEOLOGICAL_TOURISM = 'GEOLOGICAL TOURISM'
    HERITAGE_TOURISM = 'HERITAGE TOURISM'
    HUNTING_TOURISM = 'HUNTING TOURISM'
    INDUSTRIAL_TOURISM = 'INDUSTRIAL TOURISM'
    LANGUAGE_TOURISM = 'LANGUAGE TOURISM'
    LGTBI_TOURISM = 'LGTBI TOURISM'
    LUXURY_TOURISM = 'LUXURY TOURISM'
    MEDICAL_TOURISM = 'MEDICAL TOURISM'
    MEMORIAL_TOURISM = 'MEMORIAL TOURISM'
    MICE_TOURISM = 'MICE TOURISM'
    NATURE_TOURISM = 'NATURE TOURISM'
    OLIVE_OIL_TOURISM = 'OLIVE OIL TOURISM'
    PARTY_TOURISM = 'PARTY TOURISM'
    PHOTOGRAPHY_TOURISM = 'PHOTOGRAPHY TOURISM'
    RELIGIOUS_TOURISM = 'RELIGIOUS TOURISM'
    ROMANTIC_TOURISM = 'ROMANTIC TOURISM'
    RURAL_TOURISM = 'RURAL TOURISM'
    SAFARI_TOURISM = 'SAFARI TOURISM'
    SAILING_TOURISM = 'SAILING TOURISM'
    SENIOR_TOURISM = 'SENIOR TOURISM'
    SHOPPING_TOURISM = 'SHOPPING TOURISM'
    SHORT_BREAK_TOURISM = 'SHORT BREAK TOURISM'
    SINGLES_TOURISM = 'SINGLES TOURISM'
    SPORTS_TOURISM = 'SPORTS TOURISM'
    TOURISM = 'TOURISM'
    TREKKING_TOURISM = 'TREKKING TOURISM'
    URBAN_TOURISM = 'URBAN TOURISM'
    WATER_SPORTS_TOURISM = 'WATER SPORTS TOURISM'
    WEDDING___HONEYMOON_TOURISM = 'WEDDING & HONEYMOON TOURISM'
    WELLNESS_TOURISM = 'WELLNESS TOURISM'
    WHISKY_TOURISM = 'WHISKY TOURISM'
    WINE_TOURISM = 'WINE TOURISM'
    WINTER_SPORTS_TOURISM = 'WINTER SPORTS TOURISM'
    WOMEN_TOURISM = 'WOMEN TOURISM'


class IsAccessibleForFree(RootModel[bool]):
    root: bool = Field(
        ...,
        description="Property. Model:'https://schema.org/isAccessibleForFree'. A flag to signal that the item, event, or place is accessible for free.",
    )


class PublicAccess(RootModel[bool]):
    root: bool = Field(
        ...,
        description="Property. Model:'https://schema.org/publicAccess'. A flag to signal that the Place is open to public visitors. If this property is omitted there is no assumed default boolean value",
    )


class AvailableLanguageEnum(Enum):
    AD = 'AD'
    AE = 'AE'
    AF = 'AF'
    AG = 'AG'
    AI = 'AI'
    AL = 'AL'
    AM = 'AM'
    AO = 'AO'
    AQ = 'AQ'
    AR = 'AR'
    AS = 'AS'
    AT = 'AT'
    AU = 'AU'
    AW = 'AW'
    AX = 'AX'
    AZ = 'AZ'
    BA = 'BA'
    BB = 'BB'
    BD = 'BD'
    BE = 'BE'
    BF = 'BF'
    BG = 'BG'
    BH = 'BH'
    BI = 'BI'
    BJ = 'BJ'
    BL = 'BL'
    BM = 'BM'
    BN = 'BN'
    BO = 'BO'
    BQ = 'BQ'
    BR = 'BR'
    BS = 'BS'
    BT = 'BT'
    BV = 'BV'
    BW = 'BW'
    BY = 'BY'
    BZ = 'BZ'
    CA = 'CA'
    CC = 'CC'
    CD = 'CD'
    CF = 'CF'
    CG = 'CG'
    CH = 'CH'
    CI = 'CI'
    CK = 'CK'
    CL = 'CL'
    CM = 'CM'
    CN = 'CN'
    CO = 'CO'
    CR = 'CR'
    CU = 'CU'
    CV = 'CV'
    CW = 'CW'
    CX = 'CX'
    CY = 'CY'
    CZ = 'CZ'
    DE = 'DE'
    DJ = 'DJ'
    DK = 'DK'
    DM = 'DM'
    DO = 'DO'
    DZ = 'DZ'
    EC = 'EC'
    EE = 'EE'
    EG = 'EG'
    EH = 'EH'
    ER = 'ER'
    ES = 'ES'
    ET = 'ET'
    FI = 'FI'
    FJ = 'FJ'
    FK = 'FK'
    FM = 'FM'
    FO = 'FO'
    FR = 'FR'
    GA = 'GA'
    GB = 'GB'
    GD = 'GD'
    GE = 'GE'
    GF = 'GF'
    GG = 'GG'
    GH = 'GH'
    GI = 'GI'
    GL = 'GL'
    GM = 'GM'
    GN = 'GN'
    GP = 'GP'
    GQ = 'GQ'
    GR = 'GR'
    GS = 'GS'
    GT = 'GT'
    GU = 'GU'
    GW = 'GW'
    GY = 'GY'
    HK = 'HK'
    HM = 'HM'
    HN = 'HN'
    HR = 'HR'
    HT = 'HT'
    HU = 'HU'
    ID = 'ID'
    IE = 'IE'
    IL = 'IL'
    IM = 'IM'
    IN = 'IN'
    IO = 'IO'
    IQ = 'IQ'
    IR = 'IR'
    IS = 'IS'
    IT = 'IT'
    JE = 'JE'
    JM = 'JM'
    JO = 'JO'
    JP = 'JP'
    KE = 'KE'
    KG = 'KG'
    KH = 'KH'
    KI = 'KI'
    KM = 'KM'
    KN = 'KN'
    KP = 'KP'
    KR = 'KR'
    KW = 'KW'
    KY = 'KY'
    KZ = 'KZ'
    LA = 'LA'
    LB = 'LB'
    LC = 'LC'
    LI = 'LI'
    LK = 'LK'
    LR = 'LR'
    LS = 'LS'
    LT = 'LT'
    LU = 'LU'
    LV = 'LV'
    LY = 'LY'
    MA = 'MA'
    MC = 'MC'
    MD = 'MD'
    ME = 'ME'
    MF = 'MF'
    MG = 'MG'
    MH = 'MH'
    MK = 'MK'
    ML = 'ML'
    MM = 'MM'
    MN = 'MN'
    MO = 'MO'
    MP = 'MP'
    MQ = 'MQ'
    MR = 'MR'
    MS = 'MS'
    MT = 'MT'
    MU = 'MU'
    MV = 'MV'
    MW = 'MW'
    MX = 'MX'
    MY = 'MY'
    MZ = 'MZ'
    NA = 'NA'
    NC = 'NC'
    NE = 'NE'
    NF = 'NF'
    NG = 'NG'
    NI = 'NI'
    NL = 'NL'
    NO = 'NO'
    NP = 'NP'
    NR = 'NR'
    NU = 'NU'
    NZ = 'NZ'
    OM = 'OM'
    PA = 'PA'
    PE = 'PE'
    PF = 'PF'
    PG = 'PG'
    PH = 'PH'
    PK = 'PK'
    PL = 'PL'
    PM = 'PM'
    PN = 'PN'
    PR = 'PR'
    PS = 'PS'
    PT = 'PT'
    PW = 'PW'
    PY = 'PY'
    QA = 'QA'
    RE = 'RE'
    RO = 'RO'
    RS = 'RS'
    RU = 'RU'
    RW = 'RW'
    SA = 'SA'
    SB = 'SB'
    SC = 'SC'
    SD = 'SD'
    SE = 'SE'
    SG = 'SG'
    SH = 'SH'
    SI = 'SI'
    SJ = 'SJ'
    SK = 'SK'
    SL = 'SL'
    SM = 'SM'
    SN = 'SN'
    SO = 'SO'
    SR = 'SR'
    SS = 'SS'
    ST = 'ST'
    SV = 'SV'
    SX = 'SX'
    SY = 'SY'
    SZ = 'SZ'
    TC = 'TC'
    TD = 'TD'
    TF = 'TF'
    TG = 'TG'
    TH = 'TH'
    TJ = 'TJ'
    TK = 'TK'
    TL = 'TL'
    TM = 'TM'
    TN = 'TN'
    TO = 'TO'
    TR = 'TR'
    TT = 'TT'
    TV = 'TV'
    TW = 'TW'
    TZ = 'TZ'
    UA = 'UA'
    UG = 'UG'
    UM = 'UM'
    US = 'US'
    UY = 'UY'
    UZ = 'UZ'
    VA = 'VA'
    VC = 'VC'
    VE = 'VE'
    VG = 'VG'
    VI = 'VI'
    VN = 'VN'
    VU = 'VU'
    WF = 'WF'
    WS = 'WS'
    YE = 'YE'
    YT = 'YT'
    ZA = 'ZA'
    ZM = 'ZM'
    ZW = 'ZW'


class AvailableLanguage(RootModel[List[AvailableLanguageEnum]]):
    root: List[AvailableLanguageEnum] = Field(
        ...,
        description="Property. Model:''. A language someone may use with or at the item, service or place. Please use one of the language codes from the IETF BCP 47 standard. ",
    )


class Video(RootModel[AnyUrl]):
    root: AnyUrl = Field(
        ...,
        description="Property. Model:'https://schema.org/URL'. Url with video related to the item",
    )


class GSMACommons(BaseModel):
    id: Optional[EntityIdentifierType] = None
    dateCreated: Optional[AwareDatetime] = Field(
        None,
        description='Property. Entity creation timestamp. This will usually be allocated by the storage platform',
    )
    dateModified: Optional[AwareDatetime] = Field(
        None,
        description='Property. Timestamp of the last modification of the entity. This will usually be allocated by the storage platform',
    )
    source: Optional[str] = Field(
        None,
        description='Property. A sequence of characters giving the original source of the entity data as a URL. Recommended to be the fully qualified domain name of the source provider, or the URL to the source object',
    )
    name: Optional[str] = Field(None, description='Property. The name of this item')
    alternateName: Optional[str] = Field(
        None, description='Property. An alternative name for this item'
    )
    description: Optional[str] = Field(
        None, description='Property. A description of this item'
    )
    dataProvider: Optional[str] = Field(
        None,
        description='Property. A sequence of characters identifying the provider of the harmonised data entity',
    )
    owner: Optional[List[EntityIdentifierType]] = Field(
        None,
        description='Property. A List containing a JSON encoded sequence of characters referencing the unique Ids of the owner(s)',
    )
    seeAlso: Optional[Union[List[AnyUrl], AnyUrl]] = Field(
        None,
        description='Property. list of uri pointing to additional resources about the item',
    )


class WaterQualityObservedCatSchema(GSMACommons, LocationCommons):
    type: Type = Field(
        ...,
        description='Property. NGSI Entity type. It has to be WaterQualityObservedCAT',
    )
    dateObserved: constr(pattern=r'^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$') = Field(
        ...,
        description="Property. Model:'https://schema.org/DateTime'. The date and time of this observation in ISO8601 UTCformat (yyyy-MM-dd hh:mm:ss.sss). It can be represented by an specific time instant or by an ISO8601 interval",
    )
    measurand: Optional[List[str]] = Field(
        None,
        description='Property. An array of strings containing details (see format below) about extra measurands provided by this observation',
        min_length=1,
    )
    temperature: Optional[float] = Field(None, description='Property. Temperature')
    bod: Optional[confloat(ge=0.0)] = Field(
        None,
        description="Property. Biochemical oxygen demand (BOD) is the amount of dissolved oxygen (DO) needed (i.e. demanded) by aerobic biological organisms to break down organic material present in a given water sample at certain temperature over a specific time period. Units:'mg/l'",
    )
    cod: Optional[confloat(ge=0.0)] = Field(
        None,
        description="Property. Chemical oxygen demand (COD) is an indicative measure of the amount of oxygen that can be consumed by reactions in a measured solution. Units:'mg/l'",
    )
    conductivity: Optional[conint(ge=0)] = Field(
        None, description='Property. Electrical Conductivity'
    )
    conductance: Optional[confloat(ge=0.0)] = Field(
        None, description='Property. Specific Conductance'
    )
    tss: Optional[confloat(ge=0.0)] = Field(
        None, description='Property. Total suspended solids'
    )
    tds: Optional[confloat(ge=0.0)] = Field(
        None, description='Property. Total dissolved solids. '
    )
    turbidity: Optional[confloat(ge=0.0, multiple_of=0.1)] = Field(
        None,
        description='Property. Amount of light scattered by particles in the water column',
    )
    salinity: Optional[confloat(ge=0.0)] = Field(
        None, description='Property. Amount of salts dissolved in water'
    )
    pH: Optional[confloat(ge=0.0, le=14.0, multiple_of=0.1)] = Field(
        None, description='Property. Acidity or basicity of an aqueous solution'
    )
    orp: Optional[conint(ge=0)] = Field(
        None, description='Property. Oxidation-Reduction potential'
    )
    O2: Optional[confloat(ge=0.0)] = Field(
        None, description='Property. Level of free, non-compound oxygen present'
    )
    Chla: Optional[confloat(ge=0.0)] = Field(
        None, description='Property. Concentration of chlorophyll A'
    )
    PE: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Property. Concentration of pigment phycoerythrin which can be measured to estimate cyanobacteria concentrations specifically',
    )
    PC: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Property. Concentration of pigment phycocyanin which can be measured to estimate cyanobacteria concentrations specifically',
    )
    NH4: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None, description='Property. Concentration of ammonium'
    )
    NH3: Optional[confloat(ge=0.0)] = Field(
        None, description='Property. Concentration of ammonia'
    )
    Cl_: Optional[confloat(ge=0.0)] = Field(
        None, alias='Cl-', description='Property. Concentration of chlorides'
    )
    Vinyl_chloride: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None,
        alias='Vinyl chloride',
        description='Property. Concentration of vinyl chloride',
    )
    NO3: Optional[conint(ge=0)] = Field(
        None, description='Property. Concentration of nitrates'
    )
    PO4: Optional[confloat(ge=0.0)] = Field(
        None, description='Property. Concentration of phosphates'
    )
    escherichiaColi: Optional[conint(ge=0)] = Field(
        None,
        description="Property. Concentration of Escherichia coli. Units:'Total number of bacteria/100mL'",
    )
    enterococci: Optional[conint(ge=0)] = Field(
        None,
        description="Property. Concentration of Enterococci. Units:'Total number of bacteria/100mL'",
    )
    refPointOfInterest: Optional[
        Union[
            constr(
                pattern=r'^[\w\-\.\{\}\$\+\*\[\]`|~^@!, :\\]+$',
                min_length=1,
                max_length=256,
            ),
            AnyUrl,
        ]
    ] = Field(
        None,
        description='Relationship. A reference to a point of interest associated to this observation',
    )
    flow: Optional[confloat(multiple_of=0.1)] = Field(
        None, description="Property. Units:'litres/second'. Water Flow observed. "
    )
    alkalinity: Optional[confloat(ge=0.0)] = Field(
        None,
        description="Property. The alkalinity of water is its acid-neutralizing capacity comprised of the total of all titratable bases. Units:'mg/l'",
    )
    TKN: Optional[confloat(ge=0.0)] = Field(
        None,
        description="Property. Total Kjeldahl Nitrogen. A measure that determines both the organic and the inorganic forms of nitrogen. Units:'mg/l'",
    )
    NO2: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None,
        description="Property. Nitrite nitrogen. Concentration of a sample in nitrite nitrogen. Units:'mg/l'",
    )
    N_TOT: Optional[confloat(ge=0.0)] = Field(
        None,
        alias='N-TOT',
        description="Property. Total Nitrogen. Total Nitrogen (TN) is the sum of nitrate-nitrogen (NO3-N), nitrite-nitrogen (NO2-N), ammonia-nitrogen (NH3-N) and organically bonded nitrogen. Units:'mg/l'",
    )
    P_TOT: Optional[confloat(ge=0.0)] = Field(
        None,
        alias='P-TOT',
        description="Property. Total Phosphorus. Total phosphorus is a measure of all forms of\xa0phosphorus\xa0in the water, including dissolved and particulate, organic and inorganic. Units:'mg/l'",
    )
    P_PO4: Optional[confloat(ge=0.0)] = Field(
        None,
        alias='P-PO4',
        description="Property. Phosphate-phosphorus. Concentration of phosphorus as phosphate. Units:'mg/l'",
    )
    Al: Optional[conint(ge=0)] = Field(
        None,
        description="Property. Aluminium. Concentration of aluminium. Units:'mg/l'",
    )
    As: Optional[conint(ge=0)] = Field(
        None, description="Property. Arsenic. Concentration of arsenic. Units:'mg/l'"
    )
    B: Optional[confloat(ge=0.0, multiple_of=0.1)] = Field(
        None, description="Property. Boron. Concentration of boron. Units:'mg/l'"
    )
    Ba: Optional[confloat(ge=0.0)] = Field(
        None, description="Property. Barium. Concentration of barium. Units:'mg/l'"
    )
    Cd: Optional[confloat(ge=0.0, multiple_of=0.1)] = Field(
        None, description="Property. Cadmium. Concentration of cadmium. Units:'ug/l'"
    )
    Cr: Optional[conint(ge=0)] = Field(
        None,
        description="Property. Chromium. Concentration of total chromium oxidation state +3 and oxidation state +6. Units:'ug/L'",
    )
    Cr_III: Optional[conint(ge=0)] = Field(
        None,
        alias='Cr-III',
        description="Property. Chromium III. Concentration of chromium at the oxidation state +3. Units:'ug/l'",
    )
    Cr_VI: Optional[conint(ge=0)] = Field(
        None,
        alias='Cr-VI',
        description="Property. Chromium VI. Concentration of chromium at the oxidation state +6. Units:'ug/l'",
    )
    Cu: Optional[confloat(ge=0.0, multiple_of=0.1)] = Field(
        None, description="Property. Copper. Concentration of copper. Units:'mg/l'"
    )
    Fe: Optional[conint(ge=0)] = Field(
        None, description="Property. Iron. Concentration of iron. Units:'ug/l'"
    )
    fluoride: Optional[confloat(ge=0.0, multiple_of=0.1)] = Field(
        None, description="Property. Concentration of fluoride. Units:'mg/l'"
    )
    Hg: Optional[confloat(ge=0.0, multiple_of=0.1)] = Field(
        None, description="Property. Mercury. Concentration of mercury. Units:'ug/l'"
    )
    THC: Optional[confloat(ge=0.0)] = Field(
        None,
        description="Property. Total hydrocarbon. Concentration of total hydrocarbon. Units:'mg/l'",
    )
    THPA: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None,
        description="Property. Total hydrocarbon. Concentration of polycyclic aromatic hydrocarbons. Units:'ug/l'",
    )
    Ni: Optional[conint(ge=0)] = Field(
        None, description="Property. Nickel. Concentration of Nickel. Units:'ug/l'"
    )
    TO: Optional[confloat(ge=0.0)] = Field(
        None,
        description="Property. Total oil content. Concentration of oil. Units:'mg/l'",
    )
    Pb: Optional[confloat(ge=0.0, multiple_of=0.1)] = Field(
        None, description="Property. Lead. Concentration of lead. Units:'ug/l'"
    )
    Se: Optional[conint(ge=0)] = Field(
        None, description="Property. Selenium. Concentration of selenium. Units:'ug/l'"
    )
    Sn: Optional[confloat(ge=0.0)] = Field(
        None, description="Property. Tin. Concentration of tin. Units:'mg/l'"
    )
    sulphate: Optional[conint(ge=0)] = Field(
        None, description="Property. Concentration of sulfate. Units:'mg/l'"
    )
    sulphite: Optional[confloat(ge=0.0)] = Field(
        None, description="Property. Concentration of sulfite. Units:'mg/l'"
    )
    anionic_surfactants: Optional[confloat(ge=0.0)] = Field(
        None,
        alias='anionic-surfactants',
        description="Property. Concentration of anionic surfactants. Units:'mg/l'",
    )
    cationic_surfactants: Optional[confloat(ge=0.0)] = Field(
        None,
        alias='cationic-surfactants',
        description="Property. Concentrtation of cationic surfactants. Units:'mg/l'",
    )
    non_ionic_surfactants: Optional[confloat(ge=0.0)] = Field(
        None,
        alias='non-ionic-surfactants',
        description="Property. Concentration of non-ionic surfactants. Units:'mg/l'",
    )
    total_surfactants: Optional[confloat(ge=0.0)] = Field(
        None,
        alias='total-surfactants',
        description="Property. Concentration of total surfactants. Units:'mg/l'",
    )
    Zn: Optional[confloat(ge=0.0)] = Field(
        None, description="Property. Zinc. Concentration of zinc. Units:'mg/l'"
    )
    ColorTrue: Optional[confloat(ge=0.0, multiple_of=0.1)] = Field(
        None, description="Property. Color True. Units:'Hazen'"
    )
    ColorApp: Optional[confloat(ge=0.0, multiple_of=0.1)] = Field(
        None, description="Property. Color App. Units:'Hazen'"
    )
    turbidityEPA: Optional[confloat(ge=0.0, multiple_of=0.1)] = Field(
        None, description='Property. Turbidity by EPA specification'
    )
    turbidityISO: Optional[confloat(ge=0.0, multiple_of=0.1)] = Field(
        None, description='Property. Turbidity by ISO specification iSCAN sensor'
    )
    turbiditySigrist: Optional[confloat(ge=0.0, multiple_of=0.1)] = Field(
        None, description='Property. Turbidity by ISO specification by Sigrist sensor'
    )
    TOC: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None,
        description='Property. TOC. Concentration of Total Organic Carbon. Units mg/L',
    )
    DOC: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None,
        description='Property. DOC. Concentration of Dissolved Organic Carbon. Units mg/L',
    )
    UV254: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None,
        description='Property. UV254. organic matter present in water. Units Abs/m',
    )
    Cl: Optional[confloat(ge=0.0, multiple_of=0.01)] = Field(
        None,
        description='Property. Free Chlorine. Chlorine concentratrion in water. Units mg/L',
    )
    TLF: Optional[TLF] = Field(None, description='Property. TLF')
    id: EntityIdentifierType
    location: Union[Location, Location1, Location2, Location3, Location4, Location5] = (
        Field(
            ...,
            description='GeoProperty. Geojson reference to the item. It can be Point, LineString, Polygon, MultiPoint, MultiLineString or MultiPolygon',
        )
    )
