# generated by datamodel-codegen:
#   filename:  schema_test.json
#   timestamp: 2024-07-10T11:24:31+00:00

from __future__ import annotations

from typing import Any

from pydantic import RootModel


class Model(RootModel):
    __root__root: Any
